### ISSUE TITLE
Request: Counting bloom filter function to get current value

### ISSUE THREAD

**Issue by glmcdona** [yankun1992/fastbloom#3]
Another request if possible. For the counting bloom filter, is it possible add a function to get the current count?

Eg:
```python
cbf.add("asdf")
cbf.add("asdf")
print(cbf.count("asdf")) --> 2
print(cbf.count("abcd")) --> 0
```

Not sure if this is possible since I'm not a bloom filter expert. I think looking at the code it uses 4 bits for the counting, so will be encoding a count between 0 and 15 to track the count, right?

**Comment by yankun1992** [comment]
It is possible to provide an api to return the count, but due to the principle of the counting bloom filter itself, this count is not an accurate statistic, but only a rough estimate, and if too much elements are inserted to this bloom filter, the more inaccurate this estimate will be. Does this meet your needs?

**Comment by glmcdona** [comment]
Yes, that works for the scenario I am working on. And the current 4 bits of counting works perfect for my scenario. Appreciate it @yankun1992!

**Comment by yankun1992** [comment]
In CountingBloomFilter, add methods `estimate_count` and `counter_at` to support this fearure.
Usage examples can be find at https://github.com/yankun1992/fastbloom/blob/main/py_tests/test_counting_bloom_filter.py#L96
